# Generated by Django 4.0 on 2021-12-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otoshimonoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otoshimonoinfo',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
