# Generated by Django 4.0 on 2021-12-25 08:46
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'otoshimonoapp/fixtures/init_data.json', app_label='otoshimonoapp')

class Migration(migrations.Migration):

    dependencies = [
        ('otoshimonoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
